import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, decimal, boolean, json } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  subscriptionPlan: mysqlEnum("subscriptionPlan", ["free", "starter", "professional", "enterprise"]).default("free").notNull(),
  subscriptionStatus: mysqlEnum("subscriptionStatus", ["active", "cancelled", "expired"]).default("active").notNull(),
  subscriptionExpiresAt: timestamp("subscriptionExpiresAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Mercado Libre accounts linked to users
 */
export const mlAccounts = mysqlTable("ml_accounts", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  mlUserId: varchar("mlUserId", { length: 64 }).notNull().unique(),
  nickname: varchar("nickname", { length: 255 }),
  email: varchar("email", { length: 320 }),
  accessToken: text("accessToken").notNull(),
  refreshToken: text("refreshToken").notNull(),
  tokenExpiresAt: timestamp("tokenExpiresAt").notNull(),
  siteId: varchar("siteId", { length: 10 }).notNull(), // MLA, MLB, etc.
  accountStatus: mysqlEnum("accountStatus", ["active", "suspended", "restricted", "blocked"]).default("active").notNull(),
  riskScore: decimal("riskScore", { precision: 5, scale: 2 }).default("0.00").notNull(),
  riskLevel: mysqlEnum("riskLevel", ["low", "medium", "high", "critical"]).default("low").notNull(),
  lastSyncAt: timestamp("lastSyncAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type MlAccount = typeof mlAccounts.$inferSelect;
export type InsertMlAccount = typeof mlAccounts.$inferInsert;

/**
 * Metrics history for ML accounts
 */
export const metrics = mysqlTable("metrics", {
  id: int("id").autoincrement().primaryKey(),
  mlAccountId: int("mlAccountId").notNull(),
  date: timestamp("date").notNull(),
  // Cancellation metrics
  totalOrders: int("totalOrders").default(0).notNull(),
  cancelledOrders: int("cancelledOrders").default(0).notNull(),
  cancellationRate: decimal("cancellationRate", { precision: 5, scale: 2 }).default("0.00").notNull(),
  // Claims metrics
  totalClaims: int("totalClaims").default(0).notNull(),
  validClaims: int("validClaims").default(0).notNull(),
  excludedClaims: int("excludedClaims").default(0).notNull(),
  claimRate: decimal("claimRate", { precision: 5, scale: 2 }).default("0.00").notNull(),
  // Response time metrics
  avgResponseTime: int("avgResponseTime").default(0).notNull(), // in minutes
  lateResponses: int("lateResponses").default(0).notNull(),
  // Stock metrics
  totalListings: int("totalListings").default(0).notNull(),
  outOfStock: int("outOfStock").default(0).notNull(),
  pausedListings: int("pausedListings").default(0).notNull(),
  // Quality metrics
  listingsWithIssues: int("listingsWithIssues").default(0).notNull(),
  reputationScore: decimal("reputationScore", { precision: 5, scale: 2 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Metric = typeof metrics.$inferSelect;
export type InsertMetric = typeof metrics.$inferInsert;

/**
 * Alerts generated by the risk engine
 */
export const alerts = mysqlTable("alerts", {
  id: int("id").autoincrement().primaryKey(),
  mlAccountId: int("mlAccountId").notNull(),
  type: mysqlEnum("type", [
    "cancellation_spike",
    "claim_increase",
    "stock_critical",
    "response_delay",
    "quality_issue",
    "reputation_drop",
    "suspension_risk",
    "fiscal_warning"
  ]).notNull(),
  severity: mysqlEnum("severity", ["low", "medium", "high", "critical"]).notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  description: text("description").notNull(),
  aiSuggestion: text("aiSuggestion"), // AI-generated contextual suggestion
  actionRequired: text("actionRequired"), // Clear action translated from opaque ML rules
  status: mysqlEnum("status", ["active", "acknowledged", "resolved", "ignored"]).default("active").notNull(),
  priority: int("priority").default(0).notNull(), // AI-calculated priority
  notifiedViaEmail: boolean("notifiedViaEmail").default(false).notNull(),
  notifiedViaWhatsapp: boolean("notifiedViaWhatsapp").default(false).notNull(),
  acknowledgedAt: timestamp("acknowledgedAt"),
  resolvedAt: timestamp("resolvedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Alert = typeof alerts.$inferSelect;
export type InsertAlert = typeof alerts.$inferInsert;

/**
 * User interactions with alerts (for AI learning)
 */
export const alertInteractions = mysqlTable("alert_interactions", {
  id: int("id").autoincrement().primaryKey(),
  alertId: int("alertId").notNull(),
  mlAccountId: int("mlAccountId").notNull(),
  action: mysqlEnum("action", ["viewed", "acknowledged", "ignored", "resolved"]).notNull(),
  timeTaken: int("timeTaken"), // minutes from alert creation to action
  outcome: text("outcome"), // What happened after the alert (for learning)
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type AlertInteraction = typeof alertInteractions.$inferSelect;
export type InsertAlertInteraction = typeof alertInteractions.$inferInsert;

/**
 * Risk score history for tracking evolution
 */
export const riskHistory = mysqlTable("risk_history", {
  id: int("id").autoincrement().primaryKey(),
  mlAccountId: int("mlAccountId").notNull(),
  riskScore: decimal("riskScore", { precision: 5, scale: 2 }).notNull(),
  riskLevel: mysqlEnum("riskLevel", ["low", "medium", "high", "critical"]).notNull(),
  factors: json("factors").$type<Record<string, number>>(), // Contributing factors breakdown
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type RiskHistory = typeof riskHistory.$inferSelect;
export type InsertRiskHistory = typeof riskHistory.$inferInsert;

/**
 * Knowledge base articles
 */
export const knowledgeArticles = mysqlTable("knowledge_articles", {
  id: int("id").autoincrement().primaryKey(),
  category: mysqlEnum("category", [
    "claim_exclusion",
    "suspension_types",
    "best_practices",
    "case_studies",
    "ml_rules"
  ]).notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  slug: varchar("slug", { length: 255 }).notNull().unique(),
  content: text("content").notNull(),
  tags: json("tags").$type<string[]>(),
  viewCount: int("viewCount").default(0).notNull(),
  helpful: int("helpful").default(0).notNull(),
  notHelpful: int("notHelpful").default(0).notNull(),
  published: boolean("published").default(true).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type KnowledgeArticle = typeof knowledgeArticles.$inferSelect;
export type InsertKnowledgeArticle = typeof knowledgeArticles.$inferInsert;

/**
 * Automated reports
 */
export const reports = mysqlTable("reports", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  mlAccountId: int("mlAccountId"),
  type: mysqlEnum("type", ["weekly", "monthly"]).notNull(),
  period: varchar("period", { length: 50 }).notNull(), // e.g., "2026-W04" or "2026-01"
  risksAvoided: int("risksAvoided").default(0).notNull(),
  alertsGenerated: int("alertsGenerated").default(0).notNull(),
  alertsResolved: int("alertsResolved").default(0).notNull(),
  avgRiskScore: decimal("avgRiskScore", { precision: 5, scale: 2 }),
  recommendations: json("recommendations").$type<string[]>(),
  trends: json("trends").$type<Record<string, any>>(),
  sentAt: timestamp("sentAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Report = typeof reports.$inferSelect;
export type InsertReport = typeof reports.$inferInsert;

/**
 * Notification preferences
 */
export const notificationPreferences = mysqlTable("notification_preferences", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull().unique(),
  emailEnabled: boolean("emailEnabled").default(true).notNull(),
  whatsappEnabled: boolean("whatsappEnabled").default(false).notNull(),
  whatsappNumber: varchar("whatsappNumber", { length: 20 }),
  weeklyReportEnabled: boolean("weeklyReportEnabled").default(true).notNull(),
  monthlyReportEnabled: boolean("monthlyReportEnabled").default(true).notNull(),
  alertThreshold: mysqlEnum("alertThreshold", ["all", "medium", "high", "critical"]).default("medium").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type NotificationPreference = typeof notificationPreferences.$inferSelect;
export type InsertNotificationPreference = typeof notificationPreferences.$inferInsert;
